import type { Metadata } from "next";
import { roboto } from "@/app/fonts/fonts";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Menu from "./components/Menu";

export const metadata: Metadata = {
  title: "Game Collection",
  description: "Aerolab Code Challenge - Generated by Micael Fiordelmondo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-zinc-900 min-h-screen flex flex-col`}>
        <Menu></Menu>
        {children}
        <ToastContainer
          position="bottom-left"
          autoClose={2000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
        />
        <footer className="flex justify-center items-center w-full bg-zinc-900 h-24 text-center static"> Aerolab Coding Challenge by Micael Fiordelmondo </footer>
      </body>
    </html>
  );
}
